on: [push]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - uses: actions/checkout@v4
      - run: go test -v -count 1 -tags parse ./...
  integration:
    name: integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - uses: actions/checkout@v4
      - run: go run main.go
        working-directory: ./test/integration
